### ISSUE TITLE
Can someone build me an ISO, it doesnt build on my machine because i use Edward Snowdens OS

### ISSUE THREAD

**Issue by billyblackburn** [Zeal-Operating-System/ZealOS#112] opened 2023-06-19 01:51 UTC
i just need the Zeal-OS.iso and ill be good

**Comment by doodayev** [comment] 2023-06-19 02:49
1) Most importantly, this is not an issue with the OS or the build script. The build script is fine because it was designed with certain distros and operating systems in mind. Don't spam issues.

2) There are figuratively a gazillion ways of building this OS, both for the many Linux distros out there and on Windows. Someone who uses something other than what's relatively normal like a Debian or Ubuntu based distro or another type of "easy" distro like SteamOS 3 or Manjaro should put in the effort to learn how to get things done themselves.

3) I'm going to assume by "Edward Snowdens OS" you mean Fedora Silverblue just because that's what your previous issue implied. However if I didn't see that, I would've assumed you meant QubesOS since that's the top result when I google "Edward Snowdens OS". Does anyone call Windows "Bill Gates OS"? No. Be precise.

4) For problems like this, why didn't you just join the Discord that's mentioned in the repository? There's a lot more people active on there that could've helped you with this.

5) Be creative. You could've just made a virtual machine strictly for the sole purpose of building ZealOS. Both Virtual Box and vmware support nested virtualization. That's how I do it anyways and I've made YouTube videos that show how to do this. 

6) If you actually made use of the internet and just did a search on YouTube, you may have even found a link to the Telegram channel (in case you think Discord is too "unsafe" for you) on one of my ZealOS video uploads.
Here: https://t.me/ZealGang

**Comment by GutPuncher** [comment] 2023-06-19 04:39
Duplicate of https://github.com/Zeal-Operating-System/ZealOS/issues/110

**Closed by GutPuncher** 2023-06-19 04:39 UTC
